
/** seting action types */
export const actionTypes = {
  REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_ERROR: "REGISTER_USER_ERROR",
  REGISTER_FORM_UPDATE: "REGISTER_FORM_UPDATE"

};

/*
 * Action creators for login
 */



